"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import { Footer } from "@/components/UI/Footer";
import { Header } from "@/components/UI/Header";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <ThemeProvider attribute="class">
          <NextUIProvider>
            <Header />
            <main className="flex flex-col flex-1">{children}</main>
            <Footer />
          </NextUIProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
