"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import { Footer } from "@/components/UI/Footer";
import { Header } from "@/components/UI/Header";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col bg-light dark:bg-dark min-h-screen items-center w-screen`}
      >
        <ThemeProvider attribute="class">
          <NextUIProvider>
            <main className="flex flex-col justify-between items-center min-h-screen w-screen  p-2">
              <Header />
              {children}
              <Footer />
            </main>
          </NextUIProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
